# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap-auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ldap-auth
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      serviceAccountName: nginx-ldap-auth
      containers:
      - image: docker.io/tpimenta/nginx-ldap-auth
        name: nginx-ldap-auth
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          runAsNonRoot: true
          runAsGroup: 3000
          runAsUser: 1000
          capabilities:
            drop:
              - "all"
        command:
        - "/usr/local/bin/nginx-ldap-auth"
        - "--config"
        - "/etc/nginx-ldap-auth/config.yaml"
        ports:
        - name: http
          containerPort: 5555
        volumeMounts:
        - name: config
          mountPath: /etc/nginx-ldap-auth
        resources:
          requests:
            cpu: 1m
            memory: 5Mi
          limits:
            memory: 100Mi
      volumes:
      - name: config
        secret:
          secretName: nginx-ldap-auth
          items:
          - key: config.yaml
            path: config.yaml
