apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ldap-auth
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nginx-ldap-auth
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - "nginx-ldap-auth"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ldap-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ldap-auth
subjects:
- kind: ServiceAccount
  name: nginx-ldap-auth