# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecastle
  labels:
    app: forecastle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecastle
  template:
    metadata:
      labels:
        app: forecastle
    spec:
      serviceAccountName: forecastle
      containers:
        - name: forecastle
          image: stakater/forecastle
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            runAsNonRoot: true
            runAsGroup: 3000
            runAsUser: 1000
            capabilities:
              drop:
              - ALL
          ports:
          - name: http
            protocol: TCP
            containerPort: 3000
          volumeMounts:
          - name: forecastle-config
            mountPath: /etc/forecastle
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
      - name: forecastle-config
        configMap:
          name: forecastle-config
---
apiVersion: v1
kind: Service
metadata:
  name: forecastle
  labels:
    app: forecastle
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: forecastle
