---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: examples
    image: quay.io/sighup/furyctl-bats:v0.1.0_1.0.11
    pull: always
    depends_on: [ clone ]
    commands:
      - git config --global url."https://github.com/".insteadOf ssh://git@github.com
      - bats examples/tests.bats
    when:
      event:
      - push

  - name: integration-test
    image: quay.io/sighup/kind:v0.4.0_v1.12.0_1.0.10
    pull: always
    depends_on: [ clone ]
    environment:
      CLUSTER_HOST: docker
      TESTS: katalog/tests/tests.bats
    volumes:
      - name: dockersock
        path: /var/run
    when:
      event:
      - push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
