# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium

spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pomerium
          image: pomerium/pomerium
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          args:
            - -config
            - /etc/pomerium/policy.yml
          envFrom:
            - secretRef:
                name: pomerium-env
            - configMapRef:
                name: pomerium
          env:
            - name: SERVICES
              value: all
            - name: INSECURE_SERVER
              value: "TRUE"
            - name: JWT_CLAIMS_HEADERS
              value: "email"
            - name: LOG_LEVEL
              value: "debug"
            - name: PROXY_LOG_LEVEL
              value: "debug"
            - name: POMERIUM_DEBUG
              value: "true"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/pomerium/
              name: pomerium-policy
      volumes:
        - configMap:
            defaultMode: 420
            name: pomerium-policy
          name: pomerium-policy
