apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      serviceAccountName: cert-manager-cainjector
      containers:
      - name: cainjector
        image: "quay.io/jetstack/cert-manager-cainjector:v0.9.0"
        imagePullPolicy: Always
        args:
        - --v=2
        - --leader-election-namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
