apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cainjector
  labels: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-cainjector
  labels: {}
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificates"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "events"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - "validatingwebhookconfigurations"
  - "mutatingwebhookconfigurations"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
- apiGroups:
  - "apiregistration.k8s.io"
  resources:
  - "apiservices"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cainjector
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cainjector
subjects:
- kind: ServiceAccount
  name: cert-manager-cainjector
