---
# Source: ingress-nginx/templates/admission-webhooks/cert-manager.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-root-cert
  namespace: ingress-nginx
spec:
  secretName: ingress-nginx-root-cert
  duration: "43800h0m0s"
  issuerRef:
    name: ingress-nginx-self-signed-issuer
  commonName: "ca.webhook.ingress-nginx"
  isCA: true
  subject:
    organizations:
      - ingress-nginx
