---
# Source: ingress-nginx/templates/admission-webhooks/cert-manager.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ingress-nginx-root-issuer
  namespace: ingress-nginx
spec:
  ca:
    secretName: ingress-nginx-root-cert
