---
# Source: ingress-nginx/templates/admission-webhooks/cert-manager.yaml
# generate a server certificate for the apiservices to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
spec:
  secretName: ingress-nginx-admission
  duration: "8760h0m0s"
  issuerRef:
    name: ingress-nginx-root-issuer
  dnsNames:
    - ingress-nginx-controller-admission
    - ingress-nginx-controller-admission.ingress-nginx
    - ingress-nginx-controller-admission.ingress-nginx.svc
  subject:
    organizations:
      - ingress-nginx-admission
