apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  labels: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-leaderelection
  labels: {}
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-issuers
  labels: {}
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "issuers"
  - "issuers/status"
  verbs:
  - "update"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "issuers"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-clusterissuers
  labels: {}
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "clusterissuers"
  - "clusterissuers/status"
  verbs:
  - "update"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "clusterissuers"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-certificates
  labels: {}
rules:
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "certificates"
    - "certificates/status"
    - "certificaterequests"
    - "certificaterequests/status"
    verbs:
    - "update"
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "certificates"
    - "certificaterequests"
    - "clusterissuers"
    - "issuers"
    - "orders"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "certificates/finalizers"
    verbs:
    - "update"
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "orders"
    verbs:
    - "create"
    - "delete"
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "delete"
  - apiGroups:
    - ""
    resources:
    - "events"
    verbs:
    - "create"
    - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-orders
  labels: {}
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "orders"
  - "orders/status"
  verbs:
  - "update"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "orders"
  - "clusterissuers"
  - "issuers"
  - "challenges"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "challenges"
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "orders/finalizers"
  verbs:
  - "update"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-challenges
  labels: {}
rules:
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "challenges"
    - "challenges/status"
    verbs:
    - "update"
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "challenges"
    - "issuers"
    - "clusterissuers"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "events"
    verbs:
    - "create"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "services"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "delete"
  - apiGroups:
    - "extensions"
    resources:
    - "ingresses"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "delete"
    - "update"
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "challenges/finalizers"
    verbs:
    - "update"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-ingress-shim
  labels: {}
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificates"
  - "certificaterequests"
  verbs:
  - "create"
  - "update"
  - "delete"
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificates"
  - "certificaterequests"
  - "issuers"
  - "clusterissuers"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "extensions"
  resources:
  - "ingresses"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "extensions"
  resources:
  - "ingresses/finalizers"
  verbs:
  - "update"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-leaderelection
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-leaderelection
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-issuers
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-issuers
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-clusterissuers
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-clusterissuers
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-certificates
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-certificates
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-orders
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-orders
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-challenges
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-challenges
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-ingress-shim
  labels: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-ingress-shim
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificates"
  - "certificaterequests"
  - "issuers"
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - "certmanager.k8s.io"
  resources:
  - "certificates"
  - "certificaterequests"
  - "issuers"
  verbs:
  - "create"
  - "delete"
  - "deletecollection"
  - "patch"
  - "update"
