apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  labels: {}
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - cert-manager
  selector:
    matchLabels:
      app: cert-manager
